<?php

namespace App\Modules\Accounting\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Accounting\Models\Account;
use App\Modules\Accounting\Models\CreditNote;
use App\Modules\Accounting\Models\Invoice;
use App\Modules\Accounting\Models\JournalEntry;
use App\Modules\Accounting\Models\Payment;
use App\Modules\Accounting\Models\PurchaseInvoice;
use App\Modules\Accounting\Models\PurchasePayment;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Journal Entries — READ-ONLY audit log.
 *
 * All entries are system-generated by the relevant services
 * (InvoiceService, PurchaseInvoiceService, CreditNoteService, etc.).
 * No create / edit / delete / post / reverse actions are exposed here.
 */
class JournalEntryController extends Controller
{
    // -------------------------------------------------------------------------
    // Index — audit log with filters
    // -------------------------------------------------------------------------

    public function index(Request $request): View
    {
        $companyId = $request->user()->company_id;

        $dateFrom  = $request->query('date_from');
        $dateTo    = $request->query('date_to');
        $type      = $request->query('type');
        $status    = $request->query('status');
        $accountId = $request->query('account_id');

        $entries = JournalEntry::forTenant($companyId)
            ->with('creator:id,name')
            ->withSum('lines as total_debit',  'debit')
            ->withSum('lines as total_credit', 'credit')
            ->when($dateFrom,  fn ($q) => $q->where('entry_date', '>=', $dateFrom))
            ->when($dateTo,    fn ($q) => $q->where('entry_date', '<=', $dateTo))
            ->when($type,      fn ($q) => $q->where('reference_type', $type))
            ->when($status,    fn ($q) => $q->where('status', $status))
            ->when($accountId, fn ($q) => $q->whereHas('lines', fn ($q2) =>
                $q2->where('account_id', $accountId)
            ))
            ->orderByDesc('entry_date')
            ->orderByDesc('id')
            ->paginate(30)
            ->withQueryString();

        // For the account filter dropdown — only accounts that have journal lines
        $accounts = Account::where('tenant_id', $companyId)
            ->whereHas('journalLines')
            ->orderBy('code')
            ->get(['id', 'code', 'name']);

        // Distinct reference_types present in this company's entries
        $types = JournalEntry::forTenant($companyId)
            ->whereNotNull('reference_type')
            ->distinct()
            ->pluck('reference_type');

        return view('accounting.journal-entries.index', compact(
            'entries', 'accounts', 'types',
            'dateFrom', 'dateTo', 'type', 'status', 'accountId'
        ));
    }

    // -------------------------------------------------------------------------
    // Show — entry detail + accounting breakdown
    // -------------------------------------------------------------------------

    public function show(Request $request, JournalEntry $journalEntry): View
    {
        abort_if($journalEntry->tenant_id !== $request->user()->company_id, 403);

        $journalEntry->load([
            'lines.account',
            'creator',
            'reversalOf',
            'reversingEntry',
        ]);

        $source = $this->resolveSource($journalEntry);

        return view('accounting.journal-entries.show', compact('journalEntry', 'source'));
    }

    // -------------------------------------------------------------------------
    // Source entity resolution
    // -------------------------------------------------------------------------

    /**
     * Returns ['label'=>'…', 'url'=>'…', 'number'=>'…'] for the source entity,
     * or null when there's no linked document.
     */
    private function resolveSource(JournalEntry $entry): ?array
    {
        if (! $entry->reference_type || ! $entry->reference_id) {
            return null;
        }

        return match ($entry->reference_type) {
            'invoice' => $this->sourceFor(
                Invoice::find($entry->reference_id),
                fn ($m) => ['label' => 'فاتورة مبيعات', 'url' => route('accounting.invoices.show', $m), 'number' => $m->invoice_number]
            ),
            'payment' => $this->sourceFor(
                Payment::find($entry->reference_id),
                fn ($m) => ['label' => 'دفعة عميل', 'url' => route('accounting.invoices.show', $m->invoice_id), 'number' => "PAY-{$m->id}"]
            ),
            'purchase_invoice' => $this->sourceFor(
                PurchaseInvoice::find($entry->reference_id),
                fn ($m) => ['label' => 'فاتورة مشتريات', 'url' => route('accounting.purchase-invoices.show', $m), 'number' => $m->invoice_number]
            ),
            'purchase_payment' => $this->sourceFor(
                PurchasePayment::find($entry->reference_id),
                fn ($m) => ['label' => 'دفعة مورد', 'url' => route('accounting.purchase-invoices.show', $m->purchase_invoice_id), 'number' => "PPAY-{$m->id}"]
            ),
            'credit_note' => $this->sourceFor(
                CreditNote::find($entry->reference_id),
                fn ($m) => ['label' => 'إشعار دائن', 'url' => route('accounting.credit-notes.show', $m), 'number' => $m->credit_note_number]
            ),
            default => [
                'label'  => JournalEntry::typeLabel($entry->reference_type),
                'url'    => null,
                'number' => "#{$entry->reference_id}",
            ],
        };
    }

    private function sourceFor(mixed $model, \Closure $builder): ?array
    {
        return $model ? $builder($model) : null;
    }
}
